# Generated by Django 5.2.1 on 2025-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_model_car_alter_car_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Model_Car',
        ),
    ]
